# User Service Configuration
server:
  port: 8081

spring:
  application:
    name: user-service
  
  profiles:
    active: dev

  # Database Configuration
#  datasource:
#    url: jdbc:h2:mem:userdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-microservices_userdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Smart@89
  
  # H2 Console (for development)
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop  # Create tables on startup, drop on shutdown
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  # Enable SQL script execution
  sql:
    init:
      mode: always

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  
  instance:
    hostname: localhost
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Application Information
info:
  app:
    name: User Service
    description: Microservice for user management
    version: 1.0.0
    developer: Your Name

# Logging Configuration
logging:
  level:
    com.ecommerce.user: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] [traceId=%X{traceId}] - %msg%n"

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    driver-class-name: org.postgresql.Driver
#    username: ${DB_USERNAME:user}
#    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN
    com.ecommerce.user: INFO