# Product Service Configuration
server:
  port: 8082

spring:
  application:
    name: product-service
  
  profiles:
    active: dev

    datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-microservices_productdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Smart@89
  
  # H2 Console
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  # Enable SQL script execution
  sql:
    init:
      mode: always

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  
  instance:
    hostname: localhost
    prefer-ip-address: false
    metadata-map:
      version: 1.0.0
      description: Product catalog microservice

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Application Information
info:
  app:
    name: Product Service
    description: Product catalog and inventory management
    version: 1.0.0
    features:
      - Product CRUD operations
      - Category management
      - Inventory tracking
      - Product reviews
      - Advanced search and filtering

# Logging Configuration with JSON format
logging:
  level:
    com.ecommerce.product: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] [traceId=%X{traceId}] - %msg%n"

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

#  datasource:
#    url: jdbc:postgresql://localhost:5432/ecommerce-microservices_productdb
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: Smart@89

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN
    com.ecommerce.product: INFO